package com.example.vandrservices.domain.model

import com.google.gson.annotations.SerializedName

data class Palet(
    val localId: String,
    val lotId: String,
    val paletNumber: String?,
    val variedad: String?,
    val variety: String?,
    val grower: Int?,
    val packageSize: String?,
    val packDate: String?,
    val traceability: String?,
    val ageAtInspection: String?,
    val boxes: Int?,
    val sack: String?,
    val cases: Int?,
    val label: String?,
    val pressurePSI: String?,
    val brix: String?,
    val openAppearance: String?,
    val internalColor: String?,
    val externalColor: String?,
    val count: Int?,
    val cat: String?,
    val weight: Double?,
    val mixdSize: Double?,
    val pulpTemperature: Double?,
    val gradeMaximum: Double?,
    val gradeMinimum: Double?,
    val lengthMaximum: Double?,
    val lengthMinimum: Double?,
    val bloom: String?,
    val groundColorGreen: String?,
    val groundColorTurning: String?,
    val groundColorYellow: String?,
    val blushAverage: String?,
    val cblush: String?,
    val firmnessHard: String?,
    val firmnessSensitive: String?,
    val firmnessSoft: String?,
    val plu: String?,
    val countMin: Int?,
    val countMax: Int?,
    val totalQuality: Double?,
    val totalCondition: Double?,
    val qualityColor: String?,
    val conditionColor: String?,
    val qualityValue: String?,
    val conditionValue: String?,
    val c7_8: Int?,
    val c8_9: Int?,
    val c9_10: Int?,
    val c10_11: Int?,
    val c39: Int?,
    val c40_49: Int?,
    val c50: Int?,
    val c2_dedos: Int?,
    val c3_dedos: Int?,
    val c4_dedos: Int?,
    val c5_dedos: Int?,
    val c6_dedos: Int?,
    val c7_dedos: Int?,
    val c8_dedos: Int?,
    val c9_dedos: Int?,
    val c10_dedos: Int?,
    val c11_dedos: Int?,
    val commodity: String?,
    val totalCount: Int?
)

data class PaletToJson(
    @SerializedName("id") val id: Int?,
    @SerializedName("lot") val lot: Int?,
    @SerializedName("paletnumber") val paletNumber: String?,
    @SerializedName("variedad") val variedad: String?,
    @SerializedName("variety") val variety: String?,
    @SerializedName("grower") val grower: Int?, // recibir del lot
    @SerializedName("packagesize") val packageSize: String?,
    @SerializedName("packdate") val packDate: String?, //recibir del lot
    @SerializedName("traceability") val traceability: String?,
    @SerializedName("ageatinspection") val ageAtInspection: String?,
    @SerializedName("boxes") val boxes: Int?,
    @SerializedName("sack") val sack: String?,
    @SerializedName("cases") val cases: Int?, // recibir del lot
    @SerializedName("label") val label: String?, // recibir del lot
    @SerializedName("pressurePSI") val pressurePSI: String?,
    @SerializedName("brix") val brix: String?,
    @SerializedName("openappearance") val openAppearance: String?,
    @SerializedName("internalcolor") val internalColor: String?,
    @SerializedName("externalcolor") val externalColor: String?,
    @SerializedName("count") val count: Int?,
    @SerializedName("cat") val cat: String?,
    @SerializedName("weight") val weight: Double?,
    @SerializedName("mixdsize") val mixdSize: Double?,
    @SerializedName("pulptemperature") val pulpTemperature: Double?,
    @SerializedName("grademaximum") val gradeMaximum: Double?,
    @SerializedName("grademinimum") val gradeMinimum: Double?,
    @SerializedName("lengthmaximum") val lengthMaximum: Double?,
    @SerializedName("lengthminimum") val lengthMinimum: Double?,
    @SerializedName("bloom") val bloom: String?,
    @SerializedName("groundcolorgreen") val groundColorGreen: String?,
    @SerializedName("groundcolorturning") val groundColorTurning: String?,
    @SerializedName("groundcoloryellow") val groundColorYellow: String?,
    @SerializedName("blushAverage") val blushAverage: String?,
    @SerializedName("cblush") val cblush: String?,
    @SerializedName("firmnesshard") val firmnessHard: String?,
    @SerializedName("firmnesssensitive") val firmnessSensitive: String?,
    @SerializedName("firmnesssoft") val firmnessSoft: String?,
    @SerializedName("plu") val plu: String?,
    @SerializedName("countmin") val countMin: Int?,
    @SerializedName("countmax") val countMax: Int?,
    @SerializedName("total_quality") val totalQuality: Double?,
    @SerializedName("total_condition") val totalCondition: Double?,
    @SerializedName("quality_color") val qualityColor: String?,
    @SerializedName("condition_color") val conditionColor: String?,
    @SerializedName("quality_value") val qualityValue: String?,
    @SerializedName("condition_value") val conditionValue: String?,
    @SerializedName("c7_8") val c7_8: Int?,
    @SerializedName("c8_9") val c8_9: Int?,
    @SerializedName("c9_10") val c9_10: Int?,
    @SerializedName("c10_11") val c10_11: Int?,
    @SerializedName("c39") val c39: Int?,
    @SerializedName("c40_49") val c40_49: Int?,
    @SerializedName("c50") val c50: Int?,
    @SerializedName("c2_dedos") val c_2_dedos: Int?,
    @SerializedName("c3_dedos") val c_3_dedos: Int?,
    @SerializedName("c4_dedos") val c_4_dedos: Int?,
    @SerializedName("c5_dedos") val c_5_dedos: Int?,
    @SerializedName("c6_dedos") val c_6_dedos: Int?,
    @SerializedName("c7_dedos") val c_7_dedos: Int?,
    @SerializedName("c8_dedos") val c_8_dedos: Int?,
    @SerializedName("c9_dedos") val c_9_dedos: Int?,
    @SerializedName("c10_dedos") val c_10_dedos: Int?,
    @SerializedName("c11_dedos") val c_11_dedos: Int?,
    @SerializedName("commodity") val commodity: String?,
    @SerializedName("total_count") val totalCount: Int?
)