package com.example.vandrservices.domain.model

import com.example.vandrservices.R

sealed class VarietyInfo(val name:Int) {
    data object Banana:VarietyInfo(R.string.Banana)
    data object Avocado:VarietyInfo(R.string.Avocado)
    data object Strawberrie:VarietyInfo(R.string.Strawberrie)
    data object Tomato:VarietyInfo(R.string.Tomato)
    data object Blueberrie:VarietyInfo(R.string.Blueberrie)
    data object Lemon:VarietyInfo(R.string.Lemon)
    data object Berrie:VarietyInfo(R.string.Berrie)
    data object Raspberries:VarietyInfo(R.string.Raspberries)
    data object Mangoes:VarietyInfo(R.string.Mangoes)
    data object Peppers:VarietyInfo(R.string.Peppers)
    data object Coco:VarietyInfo(R.string.Coco)
    data object Aloe_Vera:VarietyInfo(R.string.Aloe_Vera)
    data object Jicama:VarietyInfo(R.string.Jicama)
    data object Chirimoya:VarietyInfo(R.string.Chirimoya)
    data object Purple:VarietyInfo(R.string.Purple)
    data object Jackfruit:VarietyInfo(R.string.Jackfruit)
    data object Malanga:VarietyInfo(R.string.Malanga)
    data object Papaya:VarietyInfo(R.string.Papaya)
    data object Chayote:VarietyInfo(R.string.Chayote)
    data object Watermelons:VarietyInfo(R.string.Watermelons)
    data object Verdolaga:VarietyInfo(R.string.Verdolaga)
    data object Tuna:VarietyInfo(R.string.Tuna)
    data object Tomatillo:VarietyInfo(R.string.Tomatillo)
    data object Tejocote:VarietyInfo(R.string.Tejocote)
    data object Rambutan:VarietyInfo(R.string.Rambutan)
    data object Plantains:VarietyInfo(R.string.Plantains)
    data object Pitahaya:VarietyInfo(R.string.Pitahaya)
    data object Pina:VarietyInfo(R.string.Piña)
    data object Pera:VarietyInfo(R.string.Pera)
    data object Pepino:VarietyInfo(R.string.Pepino)
    data object Papalo:VarietyInfo(R.string.Papalo)
    data object Onions:VarietyInfo(R.string.Onions)
    data object Nopal:VarietyInfo(R.string.Nopal)
    data object Naranja:VarietyInfo(R.string.Naranja)
    data object Melons:VarietyInfo(R.string.Melons)
    data object Mangosteen:VarietyInfo(R.string.Mangosteen)
    data object Lettuce:VarietyInfo(R.string.Lettuce)
    data object Hoja_Platano:VarietyInfo(R.string.Hoja_Platano)
    data object Guayaba:VarietyInfo(R.string.Guayaba)
    data object Green_Onions:VarietyInfo(R.string.Green_Onions)
    data object Granada:VarietyInfo(R.string.Granada)
    data object Garlic:VarietyInfo(R.string.Garlic)
    data object Garbanzo:VarietyInfo(R.string.Garbanzo)
    data object Esparrago:VarietyInfo(R.string.Esparrago)
    data object Elote:VarietyInfo(R.string.Elote)
    data object Cilantro:VarietyInfo(R.string.Cilantro)
    data object Cauliflower:VarietyInfo(R.string.Cauliflower)
    data object Carrot:VarietyInfo(R.string.Carrot)
    data object Carambola:VarietyInfo(R.string.Carambola)
    data object Calabacita:VarietyInfo(R.string.Calabacita)
    data object Brocoli:VarietyInfo(R.string.Brocoli)
    data object Betabel:VarietyInfo(R.string.Betabel)
    data object Banana_Organic:VarietyInfo(R.string.Banana_Organic)
}

sealed class TypoImageLot(val name:String? = null){
    data object Yellow_Rust:TypoImageLot("Yellow Rust")
    data object Wounds:TypoImageLot("Wounds")
    data object White_Cells:TypoImageLot("White Cells")
    data object Weight:TypoImageLot("Weight")
    data object Vascular_Bundles:TypoImageLot("Vascular Bundles")
    data object UPC:TypoImageLot("UPC")
    data object Turning_Color:TypoImageLot("Turning Color")
    data object Truck_Plates_And_Boxes:TypoImageLot("truck plates and boxes")
    data object Transit_Rub:TypoImageLot("Transit Rub")
    data object Traceability:TypoImageLot("Traceability")
    data object Thickness:TypoImageLot("Thickness")
    data object Termografo:TypoImageLot("Termografo")
    data object Temperature_Recorder:TypoImageLot("Temperature Recorder")
    data object Temperatura_Al_Arribo:TypoImageLot("Temperatura al Arribo")
    data object Sunken:TypoImageLot("Sunken")
    data object Sun_Burn:TypoImageLot("Sun burn")
    data object Striped_Fruit:TypoImageLot("Stripped Fruit")
    data object Sprouting:TypoImageLot("Sprouting")
    data object Soft_Fruit:TypoImageLot("Soft Fruit")
    data object Shriven:TypoImageLot("Shriven")
    data object Shrivel:TypoImageLot("Shrivel")
    data object SEB:TypoImageLot("SEB")
    data object Scars:TypoImageLot("Scars")
    data object Sap_Burn:TypoImageLot("Sap Burn")
    data object Sael:TypoImageLot("Sael")
    data object Sack:TypoImageLot("Sack")
    data object Red_Cells:TypoImageLot("Red Cells")
    data object Pulp_Temperature:TypoImageLot("Pulp Temperature")
    data object Pulled_Stems:TypoImageLot("Pulled Stems")
    data object Pressure_PSI:TypoImageLot("Pressure PSI")
    data object PLU:TypoImageLot("PLU")
    data object Pallet_Appereance:TypoImageLot("Pallet Appereance")
    data object Packing_Date:TypoImageLot("Packing Date")
    data object Package_Size:TypoImageLot("Package Size")
    data object Open_Appearance_96s_Organics:TypoImageLot("Open Appearance 96's Organics")
    data object Open_Appearance_96s_CAT_2:TypoImageLot("Open Appearance 96's CAT 2")
    data object Open_Appearance_96s:TypoImageLot("Open Appearance 96's")
    data object Open_Appearance_84s_Organics:TypoImageLot("Open Appearance 84's Organics")
    data object Open_Appearance_84s_CAT_2:TypoImageLot("Open Appearance 84's CAT 2")
    data object Open_Appearance_84s:TypoImageLot("Open Appearance 84's")
    data object Open_Appearance_70s_Organics:TypoImageLot("Open Appearance 70's Organics")
    data object Open_Appearance_70s_CAT_2:TypoImageLot("Open Appearance 70's CAT 2")
    data object Open_Appearance_70s:TypoImageLot("Open Appearance 70's")
    data object Open_Appearance_60s_Organics:TypoImageLot("Open Appearance 60's Organics")
    data object Open_Appearance_60s_CAT_2:TypoImageLot("Open Appearance 60's CAT 2")
    data object Open_Appearance_60s:TypoImageLot("Open Appearance 60's")
    data object Open_Appearance_48s_Organics:TypoImageLot("Open Appearance 48's Organics")
    data object Open_Appearance_48s_CAT_2:TypoImageLot("Open Appearance 48's CAT 2")
    data object Open_Appearance_48s:TypoImageLot("Open Appearance 48's")
    data object Open_Appearance_40s_Organics:TypoImageLot("Open Appearance 40's Organics")
    data object Open_Appearance_40s_CAT_2:TypoImageLot("Open Appearance 40's CAT 2")
    data object Open_Appearance_40s:TypoImageLot("Open Appearance 40's")
    data object Open_Appearance_36s_Organics:TypoImageLot("Open Appearance 36's Organics")
    data object Open_Appearance_36s_CAT_2:TypoImageLot("Open Appearance 36's CAT 2")
    data object Open_Appearance_36s:TypoImageLot("Open Appearance 36's")
    data object Open_Appearance_32s_Organics:TypoImageLot("Open Appearance 32's Organics")
    data object Open_Appearance_32s_CAT_2:TypoImageLot("Open Appearance 32's CAT 2")
    data object Open_Appearance_32s:TypoImageLot("Open Appearance 32's")
    data object Open_Appearance:TypoImageLot("Open Appearance")
    data object Oleocellosis:TypoImageLot("Oleocellosis")
    data object Net_Weight_Size_60:TypoImageLot("Net Weight size 60")
    data object Net_Weight_Size_48:TypoImageLot("Net Weight size 48")
    data object Net_Weight_Size_36:TypoImageLot("Net Weight size 36")
    data object Net_Weight:TypoImageLot("Net Weight")
    data object Mold:TypoImageLot("Mold")
    data object Mixed_Size:TypoImageLot("Mixed Size")
    data object Mix_Size:TypoImageLot("Mix Size")
    data object Misshape:TypoImageLot("Misshape")
    data object Mechanical_Damage:TypoImageLot("Mechanical Damage")
    data object Lenticels:TypoImageLot("Lenticels")
    data object Length_Minimum:TypoImageLot("Length Minimum")
    data object Length_Maximum:TypoImageLot("Length Maximum")
    data object Leaking:TypoImageLot("Leaking")
    data object Latex:TypoImageLot("Latex")
    data object Label:TypoImageLot("Label")
    data object Internal_Color:TypoImageLot("Internal Color")
    data object Internal_Appearance:TypoImageLot("Internal Appearance")
    data object Immature:TypoImageLot("Immature")
    data object IBD:TypoImageLot("IBD")
    data object Gummosis:TypoImageLot("Gummosis")
    data object Grade_Minimum:TypoImageLot("Grade Minimum")
    data object Grade_Maximum:TypoImageLot("Grade Maximum")
    data object Freeze_Damage:TypoImageLot("Freeze Damage")
    data object Flowers_Remains:TypoImageLot("Flowers Remains")
    data object Firmness:TypoImageLot("Firmness")
    data object External_Color:TypoImageLot("External Color")
    data object Dry_Cells:TypoImageLot("Dry Cells")
    data object DPA:TypoImageLot("DPA")
    data object Discoloration:TypoImageLot("Discoloration")
    data object Diameter:TypoImageLot("Diameter")
    data object Degreening:TypoImageLot("Degreening")
    data object Decay:TypoImageLot("Decay")
    data object Condition_Canvas:TypoImageLot("condition canvas")
    data object Bruise:TypoImageLot("Bruise")
    data object Brix:TypoImageLot("Brix")
    data object Boxes:TypoImageLot("Boxes")
    data object Anthracnose:TypoImageLot("Anthracnose")
    data object Abrasion:TypoImageLot("Abrasion")
}