package com.example.vandrservices.ui.form.lot

import androidx.lifecycle.ViewModel
import com.example.vandrservices.domain.model.TypoImageLot
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import javax.inject.Inject

@HiltViewModel
class LotImgViewModel@Inject constructor(): ViewModel() {
    private var _typeImageLot = MutableStateFlow<List<TypoImageLot>>(emptyList())
    val typeImageLot: StateFlow<List<TypoImageLot>> = _typeImageLot
    init {
        _typeImageLot.value = listOf(
            TypoImageLot.Yellow_Rust,
            TypoImageLot.Wounds,
            TypoImageLot.White_Cells,
            TypoImageLot.Weight,
            TypoImageLot.Vascular_Bundles,
            TypoImageLot.UPC,
            TypoImageLot.Turning_Color,
            TypoImageLot.Truck_Plates_And_Boxes,
            TypoImageLot.Transit_Rub,
            TypoImageLot.Traceability,
            TypoImageLot.Thickness,
            TypoImageLot.Termografo,
            TypoImageLot.Temperature_Recorder,
            TypoImageLot.Temperatura_Al_Arribo,
            TypoImageLot.Sunken,
            TypoImageLot.Sun_Burn,
            TypoImageLot.Striped_Fruit,
            TypoImageLot.Sprouting,
            TypoImageLot.Soft_Fruit,
            TypoImageLot.Shriven,
            TypoImageLot.Shrivel,
            TypoImageLot.SEB,
            TypoImageLot.Scars,
            TypoImageLot.Sap_Burn,
            TypoImageLot.Sael,
            TypoImageLot.Sack,
            TypoImageLot.Red_Cells,
            TypoImageLot.Pulp_Temperature,
            TypoImageLot.Pulled_Stems,
            TypoImageLot.Pressure_PSI,
            TypoImageLot.PLU,
            TypoImageLot.Pallet_Appereance,
            TypoImageLot.Packing_Date,
            TypoImageLot.Package_Size,
            TypoImageLot.Open_Appearance_96s_Organics,
            TypoImageLot.Open_Appearance_96s_CAT_2,
            TypoImageLot.Open_Appearance_96s,
            TypoImageLot.Open_Appearance_84s_Organics,
            TypoImageLot.Open_Appearance_84s_CAT_2,
            TypoImageLot.Open_Appearance_84s,
            TypoImageLot.Open_Appearance_70s_Organics,
            TypoImageLot.Open_Appearance_70s_CAT_2,
            TypoImageLot.Open_Appearance_70s,
            TypoImageLot.Open_Appearance_60s_Organics,
            TypoImageLot.Open_Appearance_60s_CAT_2,
            TypoImageLot.Open_Appearance_60s,
            TypoImageLot.Open_Appearance_48s_Organics,
            TypoImageLot.Open_Appearance_48s_CAT_2,
            TypoImageLot.Open_Appearance_48s,
            TypoImageLot.Open_Appearance_40s_Organics,
            TypoImageLot.Open_Appearance_40s_CAT_2,
            TypoImageLot.Open_Appearance_40s,
            TypoImageLot.Open_Appearance_36s_Organics,
            TypoImageLot.Open_Appearance_36s_CAT_2,
            TypoImageLot.Open_Appearance_36s,
            TypoImageLot.Open_Appearance_32s_Organics,
            TypoImageLot.Open_Appearance_32s_CAT_2,
            TypoImageLot.Open_Appearance_32s,
            TypoImageLot.Open_Appearance,
            TypoImageLot.Oleocellosis,
            TypoImageLot.Net_Weight_Size_60,
            TypoImageLot.Net_Weight_Size_48,
            TypoImageLot.Net_Weight_Size_36,
            TypoImageLot.Net_Weight,
            TypoImageLot.Mold,
            TypoImageLot.Mixed_Size,
            TypoImageLot.Mix_Size,
            TypoImageLot.Misshape,
            TypoImageLot.Mechanical_Damage,
            TypoImageLot.Lenticels,
            TypoImageLot.Length_Minimum,
            TypoImageLot.Length_Maximum,
            TypoImageLot.Leaking,
            TypoImageLot.Latex,
            TypoImageLot.Label,
            TypoImageLot.Internal_Color,
            TypoImageLot.Internal_Appearance,
            TypoImageLot.Immature,
            TypoImageLot.IBD,
            TypoImageLot.Gummosis,
            TypoImageLot.Grade_Minimum,
            TypoImageLot.Grade_Maximum,
            TypoImageLot.Freeze_Damage,
            TypoImageLot.Flowers_Remains,
            TypoImageLot.Firmness,
            TypoImageLot.External_Color,
            TypoImageLot.Dry_Cells,
            TypoImageLot.DPA,
            TypoImageLot.Discoloration,
            TypoImageLot.Diameter,
            TypoImageLot.Degreening,
            TypoImageLot.Decay,
            TypoImageLot.Condition_Canvas,
            TypoImageLot.Bruise,
            TypoImageLot.Brix,
            TypoImageLot.Boxes,
            TypoImageLot.Anthracnose,
            TypoImageLot.Abrasion
        )
    }

}